// Code generated by ent, DO NOT EDIT.

package useraccountwindowquota

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the useraccountwindowquota type in the database.
	Label = "user_account_window_quota"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldWindowType holds the string denoting the window_type field in the database.
	FieldWindowType = "window_type"
	// FieldLimitPercent holds the string denoting the limit_percent field in the database.
	FieldLimitPercent = "limit_percent"
	// FieldAttributedPercent holds the string denoting the attributed_percent field in the database.
	FieldAttributedPercent = "attributed_percent"
	// FieldWindowResetAt holds the string denoting the window_reset_at field in the database.
	FieldWindowResetAt = "window_reset_at"
	// Table holds the table name of the useraccountwindowquota in the database.
	Table = "user_account_window_quotas"
)

// Columns holds all SQL columns for useraccountwindowquota fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldAccountID,
	FieldWindowType,
	FieldLimitPercent,
	FieldAttributedPercent,
	FieldWindowResetAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// WindowTypeValidator is a validator for the "window_type" field. It is called by the builders before save.
	WindowTypeValidator func(string) error
	// DefaultLimitPercent holds the default value on creation for the "limit_percent" field.
	DefaultLimitPercent float64
	// DefaultAttributedPercent holds the default value on creation for the "attributed_percent" field.
	DefaultAttributedPercent float64
)

// OrderOption defines the ordering options for the UserAccountWindowQuota queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByWindowType orders the results by the window_type field.
func ByWindowType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowType, opts...).ToFunc()
}

// ByLimitPercent orders the results by the limit_percent field.
func ByLimitPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLimitPercent, opts...).ToFunc()
}

// ByAttributedPercent orders the results by the attributed_percent field.
func ByAttributedPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttributedPercent, opts...).ToFunc()
}

// ByWindowResetAt orders the results by the window_reset_at field.
func ByWindowResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowResetAt, opts...).ToFunc()
}
