// Code generated by ent, DO NOT EDIT.

package useraccountwindowquota

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldAccountID, v))
}

// WindowType applies equality check predicate on the "window_type" field. It's identical to WindowTypeEQ.
func WindowType(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldWindowType, v))
}

// LimitPercent applies equality check predicate on the "limit_percent" field. It's identical to LimitPercentEQ.
func LimitPercent(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldLimitPercent, v))
}

// AttributedPercent applies equality check predicate on the "attributed_percent" field. It's identical to AttributedPercentEQ.
func AttributedPercent(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldAttributedPercent, v))
}

// WindowResetAt applies equality check predicate on the "window_reset_at" field. It's identical to WindowResetAtEQ.
func WindowResetAt(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldWindowResetAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldUserID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldAccountID, v))
}

// WindowTypeEQ applies the EQ predicate on the "window_type" field.
func WindowTypeEQ(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldWindowType, v))
}

// WindowTypeNEQ applies the NEQ predicate on the "window_type" field.
func WindowTypeNEQ(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldWindowType, v))
}

// WindowTypeIn applies the In predicate on the "window_type" field.
func WindowTypeIn(vs ...string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldWindowType, vs...))
}

// WindowTypeNotIn applies the NotIn predicate on the "window_type" field.
func WindowTypeNotIn(vs ...string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldWindowType, vs...))
}

// WindowTypeGT applies the GT predicate on the "window_type" field.
func WindowTypeGT(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldWindowType, v))
}

// WindowTypeGTE applies the GTE predicate on the "window_type" field.
func WindowTypeGTE(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldWindowType, v))
}

// WindowTypeLT applies the LT predicate on the "window_type" field.
func WindowTypeLT(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldWindowType, v))
}

// WindowTypeLTE applies the LTE predicate on the "window_type" field.
func WindowTypeLTE(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldWindowType, v))
}

// WindowTypeContains applies the Contains predicate on the "window_type" field.
func WindowTypeContains(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldContains(FieldWindowType, v))
}

// WindowTypeHasPrefix applies the HasPrefix predicate on the "window_type" field.
func WindowTypeHasPrefix(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldHasPrefix(FieldWindowType, v))
}

// WindowTypeHasSuffix applies the HasSuffix predicate on the "window_type" field.
func WindowTypeHasSuffix(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldHasSuffix(FieldWindowType, v))
}

// WindowTypeEqualFold applies the EqualFold predicate on the "window_type" field.
func WindowTypeEqualFold(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEqualFold(FieldWindowType, v))
}

// WindowTypeContainsFold applies the ContainsFold predicate on the "window_type" field.
func WindowTypeContainsFold(v string) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldContainsFold(FieldWindowType, v))
}

// LimitPercentEQ applies the EQ predicate on the "limit_percent" field.
func LimitPercentEQ(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldLimitPercent, v))
}

// LimitPercentNEQ applies the NEQ predicate on the "limit_percent" field.
func LimitPercentNEQ(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldLimitPercent, v))
}

// LimitPercentIn applies the In predicate on the "limit_percent" field.
func LimitPercentIn(vs ...float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldLimitPercent, vs...))
}

// LimitPercentNotIn applies the NotIn predicate on the "limit_percent" field.
func LimitPercentNotIn(vs ...float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldLimitPercent, vs...))
}

// LimitPercentGT applies the GT predicate on the "limit_percent" field.
func LimitPercentGT(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldLimitPercent, v))
}

// LimitPercentGTE applies the GTE predicate on the "limit_percent" field.
func LimitPercentGTE(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldLimitPercent, v))
}

// LimitPercentLT applies the LT predicate on the "limit_percent" field.
func LimitPercentLT(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldLimitPercent, v))
}

// LimitPercentLTE applies the LTE predicate on the "limit_percent" field.
func LimitPercentLTE(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldLimitPercent, v))
}

// AttributedPercentEQ applies the EQ predicate on the "attributed_percent" field.
func AttributedPercentEQ(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldAttributedPercent, v))
}

// AttributedPercentNEQ applies the NEQ predicate on the "attributed_percent" field.
func AttributedPercentNEQ(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldAttributedPercent, v))
}

// AttributedPercentIn applies the In predicate on the "attributed_percent" field.
func AttributedPercentIn(vs ...float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldAttributedPercent, vs...))
}

// AttributedPercentNotIn applies the NotIn predicate on the "attributed_percent" field.
func AttributedPercentNotIn(vs ...float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldAttributedPercent, vs...))
}

// AttributedPercentGT applies the GT predicate on the "attributed_percent" field.
func AttributedPercentGT(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldAttributedPercent, v))
}

// AttributedPercentGTE applies the GTE predicate on the "attributed_percent" field.
func AttributedPercentGTE(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldAttributedPercent, v))
}

// AttributedPercentLT applies the LT predicate on the "attributed_percent" field.
func AttributedPercentLT(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldAttributedPercent, v))
}

// AttributedPercentLTE applies the LTE predicate on the "attributed_percent" field.
func AttributedPercentLTE(v float64) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldAttributedPercent, v))
}

// WindowResetAtEQ applies the EQ predicate on the "window_reset_at" field.
func WindowResetAtEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldEQ(FieldWindowResetAt, v))
}

// WindowResetAtNEQ applies the NEQ predicate on the "window_reset_at" field.
func WindowResetAtNEQ(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNEQ(FieldWindowResetAt, v))
}

// WindowResetAtIn applies the In predicate on the "window_reset_at" field.
func WindowResetAtIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIn(FieldWindowResetAt, vs...))
}

// WindowResetAtNotIn applies the NotIn predicate on the "window_reset_at" field.
func WindowResetAtNotIn(vs ...time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotIn(FieldWindowResetAt, vs...))
}

// WindowResetAtGT applies the GT predicate on the "window_reset_at" field.
func WindowResetAtGT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGT(FieldWindowResetAt, v))
}

// WindowResetAtGTE applies the GTE predicate on the "window_reset_at" field.
func WindowResetAtGTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldGTE(FieldWindowResetAt, v))
}

// WindowResetAtLT applies the LT predicate on the "window_reset_at" field.
func WindowResetAtLT(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLT(FieldWindowResetAt, v))
}

// WindowResetAtLTE applies the LTE predicate on the "window_reset_at" field.
func WindowResetAtLTE(v time.Time) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldLTE(FieldWindowResetAt, v))
}

// WindowResetAtIsNil applies the IsNil predicate on the "window_reset_at" field.
func WindowResetAtIsNil() predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldIsNull(FieldWindowResetAt))
}

// WindowResetAtNotNil applies the NotNil predicate on the "window_reset_at" field.
func WindowResetAtNotNil() predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.FieldNotNull(FieldWindowResetAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAccountWindowQuota) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAccountWindowQuota) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAccountWindowQuota) predicate.UserAccountWindowQuota {
	return predicate.UserAccountWindowQuota(sql.NotPredicates(p))
}
