// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useraccountwindowquota"
)

// UserAccountWindowQuotaUpdate is the builder for updating UserAccountWindowQuota entities.
type UserAccountWindowQuotaUpdate struct {
	config
	hooks    []Hook
	mutation *UserAccountWindowQuotaMutation
}

// Where appends a list predicates to the UserAccountWindowQuotaUpdate builder.
func (_u *UserAccountWindowQuotaUpdate) Where(ps ...predicate.UserAccountWindowQuota) *UserAccountWindowQuotaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAccountWindowQuotaUpdate) SetUpdatedAt(v time.Time) *UserAccountWindowQuotaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserAccountWindowQuotaUpdate) SetDeletedAt(v time.Time) *UserAccountWindowQuotaUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdate) SetNillableDeletedAt(v *time.Time) *UserAccountWindowQuotaUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserAccountWindowQuotaUpdate) ClearDeletedAt() *UserAccountWindowQuotaUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAccountWindowQuotaUpdate) SetUserID(v int64) *UserAccountWindowQuotaUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdate) SetNillableUserID(v *int64) *UserAccountWindowQuotaUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAccountWindowQuotaUpdate) AddUserID(v int64) *UserAccountWindowQuotaUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UserAccountWindowQuotaUpdate) SetAccountID(v int64) *UserAccountWindowQuotaUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdate) SetNillableAccountID(v *int64) *UserAccountWindowQuotaUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UserAccountWindowQuotaUpdate) AddAccountID(v int64) *UserAccountWindowQuotaUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetWindowType sets the "window_type" field.
func (_u *UserAccountWindowQuotaUpdate) SetWindowType(v string) *UserAccountWindowQuotaUpdate {
	_u.mutation.SetWindowType(v)
	return _u
}

// SetNillableWindowType sets the "window_type" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdate) SetNillableWindowType(v *string) *UserAccountWindowQuotaUpdate {
	if v != nil {
		_u.SetWindowType(*v)
	}
	return _u
}

// SetLimitPercent sets the "limit_percent" field.
func (_u *UserAccountWindowQuotaUpdate) SetLimitPercent(v float64) *UserAccountWindowQuotaUpdate {
	_u.mutation.ResetLimitPercent()
	_u.mutation.SetLimitPercent(v)
	return _u
}

// SetNillableLimitPercent sets the "limit_percent" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdate) SetNillableLimitPercent(v *float64) *UserAccountWindowQuotaUpdate {
	if v != nil {
		_u.SetLimitPercent(*v)
	}
	return _u
}

// AddLimitPercent adds value to the "limit_percent" field.
func (_u *UserAccountWindowQuotaUpdate) AddLimitPercent(v float64) *UserAccountWindowQuotaUpdate {
	_u.mutation.AddLimitPercent(v)
	return _u
}

// SetAttributedPercent sets the "attributed_percent" field.
func (_u *UserAccountWindowQuotaUpdate) SetAttributedPercent(v float64) *UserAccountWindowQuotaUpdate {
	_u.mutation.ResetAttributedPercent()
	_u.mutation.SetAttributedPercent(v)
	return _u
}

// SetNillableAttributedPercent sets the "attributed_percent" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdate) SetNillableAttributedPercent(v *float64) *UserAccountWindowQuotaUpdate {
	if v != nil {
		_u.SetAttributedPercent(*v)
	}
	return _u
}

// AddAttributedPercent adds value to the "attributed_percent" field.
func (_u *UserAccountWindowQuotaUpdate) AddAttributedPercent(v float64) *UserAccountWindowQuotaUpdate {
	_u.mutation.AddAttributedPercent(v)
	return _u
}

// SetWindowResetAt sets the "window_reset_at" field.
func (_u *UserAccountWindowQuotaUpdate) SetWindowResetAt(v time.Time) *UserAccountWindowQuotaUpdate {
	_u.mutation.SetWindowResetAt(v)
	return _u
}

// SetNillableWindowResetAt sets the "window_reset_at" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdate) SetNillableWindowResetAt(v *time.Time) *UserAccountWindowQuotaUpdate {
	if v != nil {
		_u.SetWindowResetAt(*v)
	}
	return _u
}

// ClearWindowResetAt clears the value of the "window_reset_at" field.
func (_u *UserAccountWindowQuotaUpdate) ClearWindowResetAt() *UserAccountWindowQuotaUpdate {
	_u.mutation.ClearWindowResetAt()
	return _u
}

// Mutation returns the UserAccountWindowQuotaMutation object of the builder.
func (_u *UserAccountWindowQuotaUpdate) Mutation() *UserAccountWindowQuotaMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAccountWindowQuotaUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccountWindowQuotaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAccountWindowQuotaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccountWindowQuotaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAccountWindowQuotaUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if useraccountwindowquota.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized useraccountwindowquota.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := useraccountwindowquota.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccountWindowQuotaUpdate) check() error {
	if v, ok := _u.mutation.WindowType(); ok {
		if err := useraccountwindowquota.WindowTypeValidator(v); err != nil {
			return &ValidationError{Name: "window_type", err: fmt.Errorf(`ent: validator failed for field "UserAccountWindowQuota.window_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAccountWindowQuotaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccountwindowquota.Table, useraccountwindowquota.Columns, sqlgraph.NewFieldSpec(useraccountwindowquota.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(useraccountwindowquota.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraccountwindowquota.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraccountwindowquota.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(useraccountwindowquota.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(useraccountwindowquota.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WindowType(); ok {
		_spec.SetField(useraccountwindowquota.FieldWindowType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitPercent(); ok {
		_spec.SetField(useraccountwindowquota.FieldLimitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLimitPercent(); ok {
		_spec.AddField(useraccountwindowquota.FieldLimitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AttributedPercent(); ok {
		_spec.SetField(useraccountwindowquota.FieldAttributedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAttributedPercent(); ok {
		_spec.AddField(useraccountwindowquota.FieldAttributedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WindowResetAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldWindowResetAt, field.TypeTime, value)
	}
	if _u.mutation.WindowResetAtCleared() {
		_spec.ClearField(useraccountwindowquota.FieldWindowResetAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccountwindowquota.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAccountWindowQuotaUpdateOne is the builder for updating a single UserAccountWindowQuota entity.
type UserAccountWindowQuotaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAccountWindowQuotaMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetUpdatedAt(v time.Time) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetDeletedAt(v time.Time) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdateOne) SetNillableDeletedAt(v *time.Time) *UserAccountWindowQuotaUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserAccountWindowQuotaUpdateOne) ClearDeletedAt() *UserAccountWindowQuotaUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetUserID(v int64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdateOne) SetNillableUserID(v *int64) *UserAccountWindowQuotaUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserAccountWindowQuotaUpdateOne) AddUserID(v int64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetAccountID(v int64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdateOne) SetNillableAccountID(v *int64) *UserAccountWindowQuotaUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *UserAccountWindowQuotaUpdateOne) AddAccountID(v int64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetWindowType sets the "window_type" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetWindowType(v string) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.SetWindowType(v)
	return _u
}

// SetNillableWindowType sets the "window_type" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdateOne) SetNillableWindowType(v *string) *UserAccountWindowQuotaUpdateOne {
	if v != nil {
		_u.SetWindowType(*v)
	}
	return _u
}

// SetLimitPercent sets the "limit_percent" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetLimitPercent(v float64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.ResetLimitPercent()
	_u.mutation.SetLimitPercent(v)
	return _u
}

// SetNillableLimitPercent sets the "limit_percent" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdateOne) SetNillableLimitPercent(v *float64) *UserAccountWindowQuotaUpdateOne {
	if v != nil {
		_u.SetLimitPercent(*v)
	}
	return _u
}

// AddLimitPercent adds value to the "limit_percent" field.
func (_u *UserAccountWindowQuotaUpdateOne) AddLimitPercent(v float64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.AddLimitPercent(v)
	return _u
}

// SetAttributedPercent sets the "attributed_percent" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetAttributedPercent(v float64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.ResetAttributedPercent()
	_u.mutation.SetAttributedPercent(v)
	return _u
}

// SetNillableAttributedPercent sets the "attributed_percent" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdateOne) SetNillableAttributedPercent(v *float64) *UserAccountWindowQuotaUpdateOne {
	if v != nil {
		_u.SetAttributedPercent(*v)
	}
	return _u
}

// AddAttributedPercent adds value to the "attributed_percent" field.
func (_u *UserAccountWindowQuotaUpdateOne) AddAttributedPercent(v float64) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.AddAttributedPercent(v)
	return _u
}

// SetWindowResetAt sets the "window_reset_at" field.
func (_u *UserAccountWindowQuotaUpdateOne) SetWindowResetAt(v time.Time) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.SetWindowResetAt(v)
	return _u
}

// SetNillableWindowResetAt sets the "window_reset_at" field if the given value is not nil.
func (_u *UserAccountWindowQuotaUpdateOne) SetNillableWindowResetAt(v *time.Time) *UserAccountWindowQuotaUpdateOne {
	if v != nil {
		_u.SetWindowResetAt(*v)
	}
	return _u
}

// ClearWindowResetAt clears the value of the "window_reset_at" field.
func (_u *UserAccountWindowQuotaUpdateOne) ClearWindowResetAt() *UserAccountWindowQuotaUpdateOne {
	_u.mutation.ClearWindowResetAt()
	return _u
}

// Mutation returns the UserAccountWindowQuotaMutation object of the builder.
func (_u *UserAccountWindowQuotaUpdateOne) Mutation() *UserAccountWindowQuotaMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAccountWindowQuotaUpdate builder.
func (_u *UserAccountWindowQuotaUpdateOne) Where(ps ...predicate.UserAccountWindowQuota) *UserAccountWindowQuotaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAccountWindowQuotaUpdateOne) Select(field string, fields ...string) *UserAccountWindowQuotaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAccountWindowQuota entity.
func (_u *UserAccountWindowQuotaUpdateOne) Save(ctx context.Context) (*UserAccountWindowQuota, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccountWindowQuotaUpdateOne) SaveX(ctx context.Context) *UserAccountWindowQuota {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAccountWindowQuotaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccountWindowQuotaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAccountWindowQuotaUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if useraccountwindowquota.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized useraccountwindowquota.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := useraccountwindowquota.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccountWindowQuotaUpdateOne) check() error {
	if v, ok := _u.mutation.WindowType(); ok {
		if err := useraccountwindowquota.WindowTypeValidator(v); err != nil {
			return &ValidationError{Name: "window_type", err: fmt.Errorf(`ent: validator failed for field "UserAccountWindowQuota.window_type": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAccountWindowQuotaUpdateOne) sqlSave(ctx context.Context) (_node *UserAccountWindowQuota, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccountwindowquota.Table, useraccountwindowquota.Columns, sqlgraph.NewFieldSpec(useraccountwindowquota.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAccountWindowQuota.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraccountwindowquota.FieldID)
		for _, f := range fields {
			if !useraccountwindowquota.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraccountwindowquota.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(useraccountwindowquota.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useraccountwindowquota.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(useraccountwindowquota.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(useraccountwindowquota.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(useraccountwindowquota.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WindowType(); ok {
		_spec.SetField(useraccountwindowquota.FieldWindowType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LimitPercent(); ok {
		_spec.SetField(useraccountwindowquota.FieldLimitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLimitPercent(); ok {
		_spec.AddField(useraccountwindowquota.FieldLimitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AttributedPercent(); ok {
		_spec.SetField(useraccountwindowquota.FieldAttributedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAttributedPercent(); ok {
		_spec.AddField(useraccountwindowquota.FieldAttributedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WindowResetAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldWindowResetAt, field.TypeTime, value)
	}
	if _u.mutation.WindowResetAtCleared() {
		_spec.ClearField(useraccountwindowquota.FieldWindowResetAt, field.TypeTime)
	}
	_node = &UserAccountWindowQuota{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccountwindowquota.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
