// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/useraccountwindowquota"
)

// UserAccountWindowQuota is the model entity for the UserAccountWindowQuota schema.
type UserAccountWindowQuota struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// WindowType holds the value of the "window_type" field.
	WindowType string `json:"window_type,omitempty"`
	// LimitPercent holds the value of the "limit_percent" field.
	LimitPercent float64 `json:"limit_percent,omitempty"`
	// AttributedPercent holds the value of the "attributed_percent" field.
	AttributedPercent float64 `json:"attributed_percent,omitempty"`
	// WindowResetAt holds the value of the "window_reset_at" field.
	WindowResetAt *time.Time `json:"window_reset_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAccountWindowQuota) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useraccountwindowquota.FieldLimitPercent, useraccountwindowquota.FieldAttributedPercent:
			values[i] = new(sql.NullFloat64)
		case useraccountwindowquota.FieldID, useraccountwindowquota.FieldUserID, useraccountwindowquota.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case useraccountwindowquota.FieldWindowType:
			values[i] = new(sql.NullString)
		case useraccountwindowquota.FieldCreatedAt, useraccountwindowquota.FieldUpdatedAt, useraccountwindowquota.FieldDeletedAt, useraccountwindowquota.FieldWindowResetAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAccountWindowQuota fields.
func (_m *UserAccountWindowQuota) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useraccountwindowquota.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case useraccountwindowquota.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case useraccountwindowquota.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case useraccountwindowquota.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case useraccountwindowquota.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case useraccountwindowquota.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case useraccountwindowquota.FieldWindowType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field window_type", values[i])
			} else if value.Valid {
				_m.WindowType = value.String
			}
		case useraccountwindowquota.FieldLimitPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field limit_percent", values[i])
			} else if value.Valid {
				_m.LimitPercent = value.Float64
			}
		case useraccountwindowquota.FieldAttributedPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field attributed_percent", values[i])
			} else if value.Valid {
				_m.AttributedPercent = value.Float64
			}
		case useraccountwindowquota.FieldWindowResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_reset_at", values[i])
			} else if value.Valid {
				_m.WindowResetAt = new(time.Time)
				*_m.WindowResetAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAccountWindowQuota.
// This includes values selected through modifiers, order, etc.
func (_m *UserAccountWindowQuota) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserAccountWindowQuota.
// Note that you need to call UserAccountWindowQuota.Unwrap() before calling this method if this UserAccountWindowQuota
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAccountWindowQuota) Update() *UserAccountWindowQuotaUpdateOne {
	return NewUserAccountWindowQuotaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserAccountWindowQuota entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAccountWindowQuota) Unwrap() *UserAccountWindowQuota {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAccountWindowQuota is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserAccountWindowQuota) String() string {
	var builder strings.Builder
	builder.WriteString("UserAccountWindowQuota(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("window_type=")
	builder.WriteString(_m.WindowType)
	builder.WriteString(", ")
	builder.WriteString("limit_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.LimitPercent))
	builder.WriteString(", ")
	builder.WriteString("attributed_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttributedPercent))
	builder.WriteString(", ")
	if v := _m.WindowResetAt; v != nil {
		builder.WriteString("window_reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserAccountWindowQuotaSlice is a parsable slice of UserAccountWindowQuota.
type UserAccountWindowQuotaSlice []*UserAccountWindowQuota
