// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/useraccountwindowquota"
)

// UserAccountWindowQuotaCreate is the builder for creating a UserAccountWindowQuota entity.
type UserAccountWindowQuotaCreate struct {
	config
	mutation *UserAccountWindowQuotaMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAccountWindowQuotaCreate) SetCreatedAt(v time.Time) *UserAccountWindowQuotaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAccountWindowQuotaCreate) SetNillableCreatedAt(v *time.Time) *UserAccountWindowQuotaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAccountWindowQuotaCreate) SetUpdatedAt(v time.Time) *UserAccountWindowQuotaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAccountWindowQuotaCreate) SetNillableUpdatedAt(v *time.Time) *UserAccountWindowQuotaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserAccountWindowQuotaCreate) SetDeletedAt(v time.Time) *UserAccountWindowQuotaCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserAccountWindowQuotaCreate) SetNillableDeletedAt(v *time.Time) *UserAccountWindowQuotaCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserAccountWindowQuotaCreate) SetUserID(v int64) *UserAccountWindowQuotaCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UserAccountWindowQuotaCreate) SetAccountID(v int64) *UserAccountWindowQuotaCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetWindowType sets the "window_type" field.
func (_c *UserAccountWindowQuotaCreate) SetWindowType(v string) *UserAccountWindowQuotaCreate {
	_c.mutation.SetWindowType(v)
	return _c
}

// SetLimitPercent sets the "limit_percent" field.
func (_c *UserAccountWindowQuotaCreate) SetLimitPercent(v float64) *UserAccountWindowQuotaCreate {
	_c.mutation.SetLimitPercent(v)
	return _c
}

// SetNillableLimitPercent sets the "limit_percent" field if the given value is not nil.
func (_c *UserAccountWindowQuotaCreate) SetNillableLimitPercent(v *float64) *UserAccountWindowQuotaCreate {
	if v != nil {
		_c.SetLimitPercent(*v)
	}
	return _c
}

// SetAttributedPercent sets the "attributed_percent" field.
func (_c *UserAccountWindowQuotaCreate) SetAttributedPercent(v float64) *UserAccountWindowQuotaCreate {
	_c.mutation.SetAttributedPercent(v)
	return _c
}

// SetNillableAttributedPercent sets the "attributed_percent" field if the given value is not nil.
func (_c *UserAccountWindowQuotaCreate) SetNillableAttributedPercent(v *float64) *UserAccountWindowQuotaCreate {
	if v != nil {
		_c.SetAttributedPercent(*v)
	}
	return _c
}

// SetWindowResetAt sets the "window_reset_at" field.
func (_c *UserAccountWindowQuotaCreate) SetWindowResetAt(v time.Time) *UserAccountWindowQuotaCreate {
	_c.mutation.SetWindowResetAt(v)
	return _c
}

// SetNillableWindowResetAt sets the "window_reset_at" field if the given value is not nil.
func (_c *UserAccountWindowQuotaCreate) SetNillableWindowResetAt(v *time.Time) *UserAccountWindowQuotaCreate {
	if v != nil {
		_c.SetWindowResetAt(*v)
	}
	return _c
}

// Mutation returns the UserAccountWindowQuotaMutation object of the builder.
func (_c *UserAccountWindowQuotaCreate) Mutation() *UserAccountWindowQuotaMutation {
	return _c.mutation
}

// Save creates the UserAccountWindowQuota in the database.
func (_c *UserAccountWindowQuotaCreate) Save(ctx context.Context) (*UserAccountWindowQuota, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAccountWindowQuotaCreate) SaveX(ctx context.Context) *UserAccountWindowQuota {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAccountWindowQuotaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAccountWindowQuotaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAccountWindowQuotaCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if useraccountwindowquota.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized useraccountwindowquota.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := useraccountwindowquota.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if useraccountwindowquota.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized useraccountwindowquota.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := useraccountwindowquota.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LimitPercent(); !ok {
		v := useraccountwindowquota.DefaultLimitPercent
		_c.mutation.SetLimitPercent(v)
	}
	if _, ok := _c.mutation.AttributedPercent(); !ok {
		v := useraccountwindowquota.DefaultAttributedPercent
		_c.mutation.SetAttributedPercent(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAccountWindowQuotaCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAccountWindowQuota.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAccountWindowQuota.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAccountWindowQuota.user_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "UserAccountWindowQuota.account_id"`)}
	}
	if _, ok := _c.mutation.WindowType(); !ok {
		return &ValidationError{Name: "window_type", err: errors.New(`ent: missing required field "UserAccountWindowQuota.window_type"`)}
	}
	if v, ok := _c.mutation.WindowType(); ok {
		if err := useraccountwindowquota.WindowTypeValidator(v); err != nil {
			return &ValidationError{Name: "window_type", err: fmt.Errorf(`ent: validator failed for field "UserAccountWindowQuota.window_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LimitPercent(); !ok {
		return &ValidationError{Name: "limit_percent", err: errors.New(`ent: missing required field "UserAccountWindowQuota.limit_percent"`)}
	}
	if _, ok := _c.mutation.AttributedPercent(); !ok {
		return &ValidationError{Name: "attributed_percent", err: errors.New(`ent: missing required field "UserAccountWindowQuota.attributed_percent"`)}
	}
	return nil
}

func (_c *UserAccountWindowQuotaCreate) sqlSave(ctx context.Context) (*UserAccountWindowQuota, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAccountWindowQuotaCreate) createSpec() (*UserAccountWindowQuota, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAccountWindowQuota{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useraccountwindowquota.Table, sqlgraph.NewFieldSpec(useraccountwindowquota.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(useraccountwindowquota.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(useraccountwindowquota.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.WindowType(); ok {
		_spec.SetField(useraccountwindowquota.FieldWindowType, field.TypeString, value)
		_node.WindowType = value
	}
	if value, ok := _c.mutation.LimitPercent(); ok {
		_spec.SetField(useraccountwindowquota.FieldLimitPercent, field.TypeFloat64, value)
		_node.LimitPercent = value
	}
	if value, ok := _c.mutation.AttributedPercent(); ok {
		_spec.SetField(useraccountwindowquota.FieldAttributedPercent, field.TypeFloat64, value)
		_node.AttributedPercent = value
	}
	if value, ok := _c.mutation.WindowResetAt(); ok {
		_spec.SetField(useraccountwindowquota.FieldWindowResetAt, field.TypeTime, value)
		_node.WindowResetAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAccountWindowQuota.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAccountWindowQuotaUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAccountWindowQuotaCreate) OnConflict(opts ...sql.ConflictOption) *UserAccountWindowQuotaUpsertOne {
	_c.conflict = opts
	return &UserAccountWindowQuotaUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAccountWindowQuota.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAccountWindowQuotaCreate) OnConflictColumns(columns ...string) *UserAccountWindowQuotaUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAccountWindowQuotaUpsertOne{
		create: _c,
	}
}

type (
	// UserAccountWindowQuotaUpsertOne is the builder for "upsert"-ing
	//  one UserAccountWindowQuota node.
	UserAccountWindowQuotaUpsertOne struct {
		create *UserAccountWindowQuotaCreate
	}

	// UserAccountWindowQuotaUpsert is the "OnConflict" setter.
	UserAccountWindowQuotaUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAccountWindowQuotaUpsert) SetUpdatedAt(v time.Time) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateUpdatedAt() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserAccountWindowQuotaUpsert) SetDeletedAt(v time.Time) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateDeletedAt() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserAccountWindowQuotaUpsert) ClearDeletedAt() *UserAccountWindowQuotaUpsert {
	u.SetNull(useraccountwindowquota.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserAccountWindowQuotaUpsert) SetUserID(v int64) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateUserID() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserAccountWindowQuotaUpsert) AddUserID(v int64) *UserAccountWindowQuotaUpsert {
	u.Add(useraccountwindowquota.FieldUserID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UserAccountWindowQuotaUpsert) SetAccountID(v int64) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateAccountID() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *UserAccountWindowQuotaUpsert) AddAccountID(v int64) *UserAccountWindowQuotaUpsert {
	u.Add(useraccountwindowquota.FieldAccountID, v)
	return u
}

// SetWindowType sets the "window_type" field.
func (u *UserAccountWindowQuotaUpsert) SetWindowType(v string) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldWindowType, v)
	return u
}

// UpdateWindowType sets the "window_type" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateWindowType() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldWindowType)
	return u
}

// SetLimitPercent sets the "limit_percent" field.
func (u *UserAccountWindowQuotaUpsert) SetLimitPercent(v float64) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldLimitPercent, v)
	return u
}

// UpdateLimitPercent sets the "limit_percent" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateLimitPercent() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldLimitPercent)
	return u
}

// AddLimitPercent adds v to the "limit_percent" field.
func (u *UserAccountWindowQuotaUpsert) AddLimitPercent(v float64) *UserAccountWindowQuotaUpsert {
	u.Add(useraccountwindowquota.FieldLimitPercent, v)
	return u
}

// SetAttributedPercent sets the "attributed_percent" field.
func (u *UserAccountWindowQuotaUpsert) SetAttributedPercent(v float64) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldAttributedPercent, v)
	return u
}

// UpdateAttributedPercent sets the "attributed_percent" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateAttributedPercent() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldAttributedPercent)
	return u
}

// AddAttributedPercent adds v to the "attributed_percent" field.
func (u *UserAccountWindowQuotaUpsert) AddAttributedPercent(v float64) *UserAccountWindowQuotaUpsert {
	u.Add(useraccountwindowquota.FieldAttributedPercent, v)
	return u
}

// SetWindowResetAt sets the "window_reset_at" field.
func (u *UserAccountWindowQuotaUpsert) SetWindowResetAt(v time.Time) *UserAccountWindowQuotaUpsert {
	u.Set(useraccountwindowquota.FieldWindowResetAt, v)
	return u
}

// UpdateWindowResetAt sets the "window_reset_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsert) UpdateWindowResetAt() *UserAccountWindowQuotaUpsert {
	u.SetExcluded(useraccountwindowquota.FieldWindowResetAt)
	return u
}

// ClearWindowResetAt clears the value of the "window_reset_at" field.
func (u *UserAccountWindowQuotaUpsert) ClearWindowResetAt() *UserAccountWindowQuotaUpsert {
	u.SetNull(useraccountwindowquota.FieldWindowResetAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserAccountWindowQuota.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAccountWindowQuotaUpsertOne) UpdateNewValues() *UserAccountWindowQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useraccountwindowquota.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAccountWindowQuota.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserAccountWindowQuotaUpsertOne) Ignore() *UserAccountWindowQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAccountWindowQuotaUpsertOne) DoNothing() *UserAccountWindowQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAccountWindowQuotaCreate.OnConflict
// documentation for more info.
func (u *UserAccountWindowQuotaUpsertOne) Update(set func(*UserAccountWindowQuotaUpsert)) *UserAccountWindowQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAccountWindowQuotaUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAccountWindowQuotaUpsertOne) SetUpdatedAt(v time.Time) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateUpdatedAt() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserAccountWindowQuotaUpsertOne) SetDeletedAt(v time.Time) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateDeletedAt() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserAccountWindowQuotaUpsertOne) ClearDeletedAt() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserAccountWindowQuotaUpsertOne) SetUserID(v int64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAccountWindowQuotaUpsertOne) AddUserID(v int64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateUserID() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UserAccountWindowQuotaUpsertOne) SetAccountID(v int64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UserAccountWindowQuotaUpsertOne) AddAccountID(v int64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateAccountID() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateAccountID()
	})
}

// SetWindowType sets the "window_type" field.
func (u *UserAccountWindowQuotaUpsertOne) SetWindowType(v string) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetWindowType(v)
	})
}

// UpdateWindowType sets the "window_type" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateWindowType() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateWindowType()
	})
}

// SetLimitPercent sets the "limit_percent" field.
func (u *UserAccountWindowQuotaUpsertOne) SetLimitPercent(v float64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetLimitPercent(v)
	})
}

// AddLimitPercent adds v to the "limit_percent" field.
func (u *UserAccountWindowQuotaUpsertOne) AddLimitPercent(v float64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddLimitPercent(v)
	})
}

// UpdateLimitPercent sets the "limit_percent" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateLimitPercent() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateLimitPercent()
	})
}

// SetAttributedPercent sets the "attributed_percent" field.
func (u *UserAccountWindowQuotaUpsertOne) SetAttributedPercent(v float64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetAttributedPercent(v)
	})
}

// AddAttributedPercent adds v to the "attributed_percent" field.
func (u *UserAccountWindowQuotaUpsertOne) AddAttributedPercent(v float64) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddAttributedPercent(v)
	})
}

// UpdateAttributedPercent sets the "attributed_percent" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateAttributedPercent() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateAttributedPercent()
	})
}

// SetWindowResetAt sets the "window_reset_at" field.
func (u *UserAccountWindowQuotaUpsertOne) SetWindowResetAt(v time.Time) *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetWindowResetAt(v)
	})
}

// UpdateWindowResetAt sets the "window_reset_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertOne) UpdateWindowResetAt() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateWindowResetAt()
	})
}

// ClearWindowResetAt clears the value of the "window_reset_at" field.
func (u *UserAccountWindowQuotaUpsertOne) ClearWindowResetAt() *UserAccountWindowQuotaUpsertOne {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.ClearWindowResetAt()
	})
}

// Exec executes the query.
func (u *UserAccountWindowQuotaUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAccountWindowQuotaCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAccountWindowQuotaUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserAccountWindowQuotaUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserAccountWindowQuotaUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserAccountWindowQuotaCreateBulk is the builder for creating many UserAccountWindowQuota entities in bulk.
type UserAccountWindowQuotaCreateBulk struct {
	config
	err      error
	builders []*UserAccountWindowQuotaCreate
	conflict []sql.ConflictOption
}

// Save creates the UserAccountWindowQuota entities in the database.
func (_c *UserAccountWindowQuotaCreateBulk) Save(ctx context.Context) ([]*UserAccountWindowQuota, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAccountWindowQuota, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAccountWindowQuotaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAccountWindowQuotaCreateBulk) SaveX(ctx context.Context) []*UserAccountWindowQuota {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAccountWindowQuotaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAccountWindowQuotaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAccountWindowQuota.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAccountWindowQuotaUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAccountWindowQuotaCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserAccountWindowQuotaUpsertBulk {
	_c.conflict = opts
	return &UserAccountWindowQuotaUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAccountWindowQuota.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAccountWindowQuotaCreateBulk) OnConflictColumns(columns ...string) *UserAccountWindowQuotaUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAccountWindowQuotaUpsertBulk{
		create: _c,
	}
}

// UserAccountWindowQuotaUpsertBulk is the builder for "upsert"-ing
// a bulk of UserAccountWindowQuota nodes.
type UserAccountWindowQuotaUpsertBulk struct {
	create *UserAccountWindowQuotaCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserAccountWindowQuota.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserAccountWindowQuotaUpsertBulk) UpdateNewValues() *UserAccountWindowQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useraccountwindowquota.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAccountWindowQuota.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserAccountWindowQuotaUpsertBulk) Ignore() *UserAccountWindowQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAccountWindowQuotaUpsertBulk) DoNothing() *UserAccountWindowQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAccountWindowQuotaCreateBulk.OnConflict
// documentation for more info.
func (u *UserAccountWindowQuotaUpsertBulk) Update(set func(*UserAccountWindowQuotaUpsert)) *UserAccountWindowQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAccountWindowQuotaUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetUpdatedAt(v time.Time) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateUpdatedAt() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetDeletedAt(v time.Time) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateDeletedAt() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserAccountWindowQuotaUpsertBulk) ClearDeletedAt() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetUserID(v int64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserAccountWindowQuotaUpsertBulk) AddUserID(v int64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateUserID() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetAccountID(v int64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *UserAccountWindowQuotaUpsertBulk) AddAccountID(v int64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateAccountID() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateAccountID()
	})
}

// SetWindowType sets the "window_type" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetWindowType(v string) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetWindowType(v)
	})
}

// UpdateWindowType sets the "window_type" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateWindowType() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateWindowType()
	})
}

// SetLimitPercent sets the "limit_percent" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetLimitPercent(v float64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetLimitPercent(v)
	})
}

// AddLimitPercent adds v to the "limit_percent" field.
func (u *UserAccountWindowQuotaUpsertBulk) AddLimitPercent(v float64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddLimitPercent(v)
	})
}

// UpdateLimitPercent sets the "limit_percent" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateLimitPercent() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateLimitPercent()
	})
}

// SetAttributedPercent sets the "attributed_percent" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetAttributedPercent(v float64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetAttributedPercent(v)
	})
}

// AddAttributedPercent adds v to the "attributed_percent" field.
func (u *UserAccountWindowQuotaUpsertBulk) AddAttributedPercent(v float64) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.AddAttributedPercent(v)
	})
}

// UpdateAttributedPercent sets the "attributed_percent" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateAttributedPercent() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateAttributedPercent()
	})
}

// SetWindowResetAt sets the "window_reset_at" field.
func (u *UserAccountWindowQuotaUpsertBulk) SetWindowResetAt(v time.Time) *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.SetWindowResetAt(v)
	})
}

// UpdateWindowResetAt sets the "window_reset_at" field to the value that was provided on create.
func (u *UserAccountWindowQuotaUpsertBulk) UpdateWindowResetAt() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.UpdateWindowResetAt()
	})
}

// ClearWindowResetAt clears the value of the "window_reset_at" field.
func (u *UserAccountWindowQuotaUpsertBulk) ClearWindowResetAt() *UserAccountWindowQuotaUpsertBulk {
	return u.Update(func(s *UserAccountWindowQuotaUpsert) {
		s.ClearWindowResetAt()
	})
}

// Exec executes the query.
func (u *UserAccountWindowQuotaUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserAccountWindowQuotaCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAccountWindowQuotaCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAccountWindowQuotaUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
